---
title: Dratel Tmp
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
version: 3.2.1
exclude:
- package.json
sass:
  load_paths:
  - _sass
  - node_modules/foundation-sites/scss
